require("../node_modules/uupaa.reflection.js/lib/Reflection.js");
require("../lib/NodeModule.js");
require("../node_modules/uupaa.console.js/lib/Console.js");
require("../node_modules/uupaa.help.js/lib/Help.js");
require("../node_modules/uupaa.valid.js/lib/Valid.js");
require("../node_modules/uupaa.task.js/lib/Task.js");
require("../node_modules/uupaa.test.js/lib/Test.js");
require("../release/NodeModule.min.js");
require("./test.js");
